#include "ui.h"
#include "assets.h"      // generated by xxd
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <microhttpd.h>
#include "core/plugins.h"


static enum MHD_Result handle_api_connections(DeadlightContext *context, struct MHD_Connection *conn, const char *method);
static enum MHD_Result handle_api_nodes(DeadlightContext *context, struct MHD_Connection *conn, const char *method);
static enum MHD_Result handle_api_messages(DeadlightContext *context, struct MHD_Connection *conn, const char *method);

/* ─────────────────────────────────────────────────────────────
 * JSON string escaper
 * Handles the JSON spec (RFC 8259 §7) correctly:
 *   - Escapes " \ and control chars U+0000–U+001F
 *   - Passes valid UTF-8 multibyte sequences (emoji etc.) through
 *     unchanged — g_strescape() must NOT be used as it mangles
 *     non-ASCII bytes into octal which breaks JSON.parse().
 * Caller must g_free() the result.
 * ───────────────────────────────────────────────────────────── */
static gchar *json_escape_string(const gchar *str)
{
    if (!str) return g_strdup("");
    GString *out = g_string_sized_new(strlen(str) + 8);
    for (const gchar *p = str; *p; p++) {
        guchar c = (guchar)*p;
        switch (c) {
            case '"':  g_string_append(out, "\\\""); break;
            case '\\': g_string_append(out, "\\\\"); break;
            case '\b': g_string_append(out, "\\b");  break;
            case '\f': g_string_append(out, "\\f");  break;
            case '\n': g_string_append(out, "\\n");  break;
            case '\r': g_string_append(out, "\\r");  break;
            case '\t': g_string_append(out, "\\t");  break;
            default:
                if (c < 0x20) {
                    /* Control character — escape as \uXXXX */
                    g_string_append_printf(out, "\\u%04x", c);
                } else {
                    /* ASCII printable or UTF-8 multibyte — pass through */
                    g_string_append_c(out, (gchar)c);
                }
        }
    }
    return g_string_free(out, FALSE);
}

/* ─────────────────────────────────────────────────────────────
 * SSE client registry + broadcast
 * ───────────────────────────────────────────────────────────── */

/* Enqueue an SSE event frame for delivery by api.c's SSE timer.
 * Safe to call from any thread — api.c drains the queue on its own
 * timer tick, keeping all stream writes on a single thread.        */
void deadlight_sse_enqueue(DeadlightContext *context,
                            const gchar *event_type,
                            const gchar *json_data)
{
    if (!context || !context->pending_sse_events) return;

    gchar *frame = g_strdup_printf("event: %s\ndata: %s\n\n",
                                   event_type, json_data);
    g_mutex_lock(&context->pending_sse_mutex);
    g_queue_push_tail(context->pending_sse_events, frame);
    g_mutex_unlock(&context->pending_sse_mutex);
}

/* Drain all pending SSE frames — called by api.c timer on its thread.
 * Returns NULL-terminated array of frame strings; caller g_strfreev()s it. */
gchar **deadlight_sse_drain(DeadlightContext *context)
{
    if (!context || !context->pending_sse_events) return NULL;

    g_mutex_lock(&context->pending_sse_mutex);
    guint len = g_queue_get_length(context->pending_sse_events);
    if (len == 0) {
        g_mutex_unlock(&context->pending_sse_mutex);
        return NULL;
    }

    gchar **frames = g_new0(gchar *, len + 1);
    for (guint i = 0; i < len; i++)
        frames[i] = g_queue_pop_head(context->pending_sse_events);
    frames[len] = NULL;

    g_mutex_unlock(&context->pending_sse_mutex);
    return frames;
}

/* ---------- Simple JSON helpers ---------- */
static int json_response(struct MHD_Connection *conn, const char *json)
{
    struct MHD_Response *resp = MHD_create_response_from_buffer(strlen(json),
                                                               (void *)json,
                                                               MHD_RESPMEM_MUST_COPY);
    MHD_add_response_header(resp, "Content-Type", "application/json");
    MHD_add_response_header(resp, "Access-Control-Allow-Origin", "*");
    int ret = MHD_queue_response(conn, MHD_HTTP_OK, resp);
    MHD_destroy_response(resp);
    return ret;
}

/* ---------- Generic static file handler ---------- */
static int handle_static_file(struct MHD_Connection *conn,
                              const char *data,
                              size_t len,
                              const char *mime_type)
{
    struct MHD_Response *resp = MHD_create_response_from_buffer(
        len, (void *)data, MHD_RESPMEM_MUST_COPY);
    MHD_add_response_header(resp, "Content-Type", mime_type);
    MHD_add_response_header(resp, "Cache-Control", "public, max-age=31536000");
    int ret = MHD_queue_response(conn, MHD_HTTP_OK, resp);
    MHD_destroy_response(resp);
    return ret;
}

/* ---------- API: /api/status ---------- */
static enum MHD_Result
handle_api_status(DeadlightContext *context, struct MHD_Connection *conn, const char *method)
{
    if (strcmp(method, "GET") != 0) {
        return MHD_NO;
    }

    GString *json_str = g_string_new("{");

    g_mutex_lock(&context->stats_mutex);

    double uptime = g_timer_elapsed(context->uptime_timer, NULL);
    guint64 active_conn = context->active_connections;
    guint64 total_conn = context->total_connections;
    guint64 bytes = context->bytes_transferred;
    GList *plugin_names = deadlight_plugins_get_all_names(context);
    
    g_mutex_unlock(&context->stats_mutex);

    gchar *bytes_str = deadlight_format_bytes(bytes);

    g_string_append_printf(json_str, "\"version\": \"%s\",", DEADLIGHT_VERSION_STRING);
    g_string_append_printf(json_str, "\"uptime_seconds\": %.2f,", uptime);
    g_string_append_printf(json_str, "\"connections_active\": %" G_GUINT64_FORMAT ",", active_conn);
    g_string_append_printf(json_str, "\"connections_total\": %" G_GUINT64_FORMAT ",", total_conn);
    g_string_append_printf(json_str, "\"bytes_transferred\": %" G_GUINT64_FORMAT ",", bytes);
    g_string_append_printf(json_str, "\"bytes_transferred_formatted\": \"%s\",", bytes_str);

    g_string_append(json_str, "\"plugins\": [");
    if (plugin_names) {
        GList *iterator = plugin_names;
        gboolean first = TRUE;
        while (iterator) {
            if (!first) g_string_append(json_str, ",");
            g_string_append_printf(json_str, "\"%s\"", (gchar*)iterator->data);
            first = FALSE;
            iterator = g_list_next(iterator);
        }
        g_list_free_full(plugin_names, g_free);
    }
    g_string_append(json_str, "]}");

    enum MHD_Result ret = json_response(conn, json_str->str);

    g_free(bytes_str);
    g_string_free(json_str, TRUE);
    
    return ret;
}

/* ---------- API: /api/nodes — mesh node table ---------- */
static enum MHD_Result
handle_api_nodes(DeadlightContext *context, struct MHD_Connection *conn, const char *method)
{
    if (strcmp(method, "GET") != 0) return MHD_NO;

    GString *json_str = g_string_new("{\"nodes\":[");
    gboolean first = TRUE;

    gint64 now = g_get_real_time() / G_USEC_PER_SEC;

    g_mutex_lock(&context->node_table_mutex);

    if (context->node_table) {
        GHashTableIter iter;
        gpointer key, value;
        g_hash_table_iter_init(&iter, context->node_table);

        while (g_hash_table_iter_next(&iter, &key, &value)) {
            MeshNode *node = (MeshNode *)value;
            if (!first) g_string_append(json_str, ",");
            first = FALSE;

            /* Seconds since last heard — -1 if never updated this session */
            gint64 age = (node->last_heard > 0) ? (now - node->last_heard) : -1;

            /* Escape names defensively — they come from radio and may have
             * unexpected characters                                         */
            gchar *short_esc = json_escape_string(node->short_name);
            gchar *long_esc  = json_escape_string(node->long_name);

            g_string_append_printf(json_str,
                "{"
                "\"id\":\"%08x\","
                "\"short\":\"%s\","
                "\"long\":\"%s\","
                "\"hops\":%d,"
                "\"snr\":%.1f,"
                "\"last_heard\":%" G_GINT64_FORMAT ","   /* unix timestamp */
                "\"age_s\":%" G_GINT64_FORMAT ","        /* seconds ago    */
                "\"battery\":%u,"
                "\"has_position\":%s,"
                "\"lat\":%.6f,"
                "\"lon\":%.6f,"
                "\"alt\":%d,"
                "\"is_local\":%s"
                "}",
                node->node_id,
                short_esc,
                long_esc,
                node->hops_away,
                (double)node->snr,
                node->last_heard,
                age,
                (unsigned)node->battery_level,
                node->has_position ? "true" : "false",
                node->latitude,
                node->longitude,
                node->altitude,
                node->is_local   ? "true" : "false"
            );

            g_free(short_esc);
            g_free(long_esc);
        }
    }

    /* Also expose total count for the stat card */
    guint node_count = context->node_table
        ? g_hash_table_size(context->node_table) : 0;

    g_mutex_unlock(&context->node_table_mutex);

    g_string_append_printf(json_str, "],\"total\":%u}", node_count);

    enum MHD_Result ret = json_response(conn, json_str->str);
    g_string_free(json_str, TRUE);
    return ret;
}

/* ---------- Serve index.html ---------- */
static int handle_root(struct MHD_Connection *conn)
{
    return handle_static_file(conn, 
                             (const char *)src_ui_index_html, 
                             src_ui_index_html_len, 
                             "text/html; charset=utf-8");
}

/* ---------- Main request dispatcher ---------- */
static enum MHD_Result
request_handler(void *cls,
                struct MHD_Connection *conn,
                const char *url,
                const char *method,
                const char *version,
                const char *upload_data,
                size_t *upload_data_size,
                void **con_cls)
{
    (void)cls; (void)version; (void)upload_data; (void)upload_data_size; (void)con_cls;

    DeadlightContext *context = cls;
    
    if (strcmp(url, "/") == 0 && strcmp(method, "GET") == 0)
        return handle_root(conn);

    else if (strcmp(url, "/favicon.ico") == 0 && strcmp(method, "GET") == 0)
        return handle_static_file(conn,
                                 (const char *)src_ui_favicon_ico,
                                 src_ui_favicon_ico_len,
                                 "image/x-icon");

    else if (strcmp(url, "/favicon.png") == 0 && strcmp(method, "GET") == 0)
        return handle_static_file(conn,
                                 (const char *)src_ui_favicon_png,
                                 src_ui_favicon_png_len,
                                 "image/png");

    else if (strcmp(url, "/api/status") == 0 && strcmp(method, "GET") == 0)
        return handle_api_status(context, conn, method);

    else if (strcmp(url, "/api/connections") == 0 && strcmp(method, "GET") == 0)
        return handle_api_connections(context, conn, method);

    else if (strcmp(url, "/api/nodes") == 0 && strcmp(method, "GET") == 0)
        return handle_api_nodes(context, conn, method);

    else if (strcmp(url, "/api/messages") == 0 && strcmp(method, "GET") == 0)
        return handle_api_messages(context, conn, method);

    /* 404 */
    struct MHD_Response *resp = MHD_create_response_from_buffer(0, NULL, MHD_RESPMEM_PERSISTENT);
    int rc = MHD_queue_response(conn, MHD_HTTP_NOT_FOUND, resp);
    MHD_destroy_response(resp);
    return rc;
}

/* ---------- Server lifecycle ---------- */
static struct MHD_Daemon *ui_daemon = NULL;

void start_ui_server(DeadlightContext *context)
{
    const unsigned short ui_port = 8081;

    ui_daemon = MHD_start_daemon(MHD_USE_SELECT_INTERNALLY,
                                 ui_port,
                                 NULL,
                                 NULL,
                                 (MHD_AccessHandlerCallback) &request_handler,
                                 context, 
                                 MHD_OPTION_END);
    if (!ui_daemon)
        g_error("Failed to start UI daemon on port %u", ui_port);
    else
        g_info("UI server listening on http://127.0.0.1:%u", ui_port);
}

void stop_ui_server(void)
{
    if (ui_daemon) {
        MHD_stop_daemon(ui_daemon);
        ui_daemon = NULL;
    }
}


/* ---------- API: /api/messages — mesh text message ring buffer ---------- */
static enum MHD_Result
handle_api_messages(DeadlightContext *context, struct MHD_Connection *conn, const char *method)
{
    if (strcmp(method, "GET") != 0) return MHD_NO;

    GString *json_str = g_string_new("{\"messages\":[");
    gboolean first = TRUE;

    g_mutex_lock(&context->message_ring_mutex);

    int count = context->message_ring_count;
    int head  = context->message_ring_head;

    /* Walk oldest-to-newest so the array is chronological.
     * head points to the NEXT write slot, so oldest entry is at:
     *   (head - count + RING_SIZE) % RING_SIZE                    */
    for (int i = 0; i < count; i++) {
        int idx = (head - count + i + MESH_MESSAGE_RING_SIZE) % MESH_MESSAGE_RING_SIZE;
        MeshMessage *msg = &context->message_ring[idx];

        if (!first) g_string_append(json_str, ",");
        first = FALSE;

        gchar *text_esc = json_escape_string(msg->text);

        g_string_append_printf(json_str, "{");
        g_string_append_printf(json_str, "\"from\":\"%08x\",", msg->from_node);
        g_string_append_printf(json_str, "\"text\":\"%s\",", text_esc);
        g_string_append_printf(json_str, "\"ts\":%" G_GINT64_FORMAT ",", msg->timestamp);
        g_string_append_printf(json_str, "\"hops\":%u,", (unsigned)msg->hops);
        g_string_append_printf(json_str, "\"snr\":%.1f", (double)msg->snr);
        g_string_append_printf(json_str, "}");

        g_free(text_esc);
    }

    g_mutex_unlock(&context->message_ring_mutex);

    g_string_append_printf(json_str, "],\"total\":%d}", count);

    enum MHD_Result ret = json_response(conn, json_str->str);
    g_string_free(json_str, TRUE);
    return ret;
}

/* ---------- API: /api/connections ---------- */
static enum MHD_Result
handle_api_connections(DeadlightContext *context, struct MHD_Connection *conn, const char *method)
{
    if (strcmp(method, "GET") != 0) return MHD_NO;

    GString *json_str = g_string_new("[");
    gboolean first = TRUE;

    g_mutex_lock(&context->stats_mutex);

    if (context->connections) {
        GHashTableIter iter;
        gpointer key, value;
        g_hash_table_iter_init(&iter, context->connections);
        while (g_hash_table_iter_next(&iter, &key, &value)) {
            DeadlightConnection *d_conn = (DeadlightConnection *)value;
            if (!first) g_string_append(json_str, ",");
            g_string_append_printf(json_str, "{"
                "\"id\": %" G_GUINT64_FORMAT ","
                "\"remote\": \"%s\","
                "\"proto\": \"%s\","
                "\"tx\": %" G_GUINT64_FORMAT ","
                "\"rx\": %" G_GUINT64_FORMAT
                "}",
                d_conn->id,
                d_conn->client_address ? d_conn->client_address : "N/A",
                deadlight_protocol_to_string(d_conn->protocol),
                d_conn->bytes_client_to_upstream,
                d_conn->bytes_upstream_to_client
            );
            first = FALSE;
        }
    }

    g_mutex_unlock(&context->stats_mutex);

    g_string_append(json_str, "]");

    enum MHD_Result ret = json_response(conn, json_str->str);
    g_string_free(json_str, TRUE);
    return ret;
}